### ISSUE TITLE
Training takes a long time with 2.5K emails

### ISSUE THREAD

**Issue by fredrikburmester** [zycyc/LAMBDA#3]
Running on my M3 Pro with 18GB RAM with 2.5K emails this will take +100h. 

```
2024-11-15 12:19:34,935 - Starting training..., iters: 1000
2024-11-15 12:26:02,504 - Iter 1: Val loss 2.519, Val took 384.319s
```

What can we do about this? Thanks!

**Comment by zycyc** [comment]
I'd check out https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/LORA.md and other LORA docs for tuning hyperparams in `config.py`, but honestly train it for like 10h (100 iterations) and play around with the first adapter saved! i.e., you can control + c to exit once it's beyond 100 iterations and you see files saved in `model_output - adapters - adapters.safetensors`
