### ISSUE TITLE
_train_transformers() not found in train_model.py?

### ISSUE THREAD

**Issue by cheehk2016** [zycyc/LAMBDA#4]
_train_transformers() not found in train_model.py?

**Comment by zycyc** [comment]
yeah sorry the non-mac version hasn't been implemented. looking for someone w/ a CUDA gpu..!

**Comment by zycyc** [comment]
@cheehk2016 okay it's updated! you might want to try the latest version

**Comment by cheehk2016** [comment]
Awesome! Great work.
