### ISSUE TITLE
Issue on step 2 (train model) on Windows

### ISSUE THREAD

**Issue by fredrikburmester** [zycyc/LAMBDA#5]
I get this error after entering my HF token and trying to train the model. Maybe I have the wrong permissions on the token? 

![Screenshot 2024-11-25 145210](https://github.com/user-attachments/assets/816080e2-b357-4d62-aa4c-96b783c4c150)

**Comment by zycyc** [comment]
Hey sorry to hear that. You might want to check the .env file in your folder and make sure that is consistent with what hf gives you. It seems like you're configuring a token that's different from the active one?

**Comment by fredrikburmester** [comment]
The script asked me to insert the HF token, and I did, then this happened. So I haven't provided a token twice or anything. This is a clean run, i just pulled the latest code and ran it. I'll check the .env.

**Comment by fredrikburmester** [comment]
There was nothing wrong with the .env file from what i could see.

**Comment by fredrikburmester** [comment]
This was caused by missing `bitsandbytes`. Solved by installing:
`pip install bitsandbytes`
